### ISSUE TITLE
ERROR: command c expects \ followed by text

### ISSUE THREAD

**Issue by IsabelFE** [cfarkas/SARS-CoV-2-freebayes#1] opened 2021-07-13 17:07 UTC
Hello,

I am trying to use your pipeline and I get and error when running 
```
SARS-CoV-2-GISAID-freebayes -f cumulative_20210614/AllFasta_210617_specialreqs.fa -g ~/wuhan_trim3polyA.fasta -t 2
```

It says:
```
fixing names in FASTA file

sed: 1: "cumulative_20210614/All ...": command c expects \ followed by text
```

I would appreciate any help with this.

Thanks,

Isabel

**Comment by cfarkas** [comment] 2021-07-13 20:12
Hello IsabelFE,

By default, the pipeline expects the header from GISAID sequences, such as this one:
```
>hCoV-19/USA/DC-DFS-PHL-0803/2021|EPI_ISL_2930631|2021-03-28
```
I definitely see a bug with the sed command. Can you please provide me with one of the headers from your fasta file (starting with >)? 

Carlos

**Comment by cfarkas** [comment] 2021-07-13 20:15
Hello IsabelFE,

By default, the pipeline expects the header from GISAID sequences, such as
this one:

>hCoV-19/USA/DC-DFS-PHL-0803/2021|EPI_ISL_2930631|2021-03-28

I definitely see a bug with the sed command. Can you please provide me with
one of the headers from your fasta file (starting with >)?

Carlos

**Comment by IsabelFE** [comment] 2021-07-14 13:16
My header looks like this:

```
>2021_0412_00I13_consensus_len:29736_N:2151
```

**Comment by cfarkas** [comment] 2021-07-14 21:44
Hi IsabelFE

Your header seems totally fine. The problem is that SARS-CoV-2-GISAID-freebayes takes FASTA genomes from GISAID, with the header that GISAID provides. I added to the repository a new script called SARS-CoV-2-FASTA-freebayes (and the version with no ulimit, SARS-CoV-2-FASTA-freebayes-nolimit) in which you can pass a merged fasta file (i.e. cumulative_20210614/AllFasta_210617_specialreqs.fa) which are not from GISAID, as follows:

```
SARS-CoV-2-FASTA-freebayes.sh -f cumulative_20210614/AllFasta_210617_specialreqs.fa -g /full/path/to/SARS-CoV-2-freebayes/covid19-refseq.fasta -t 2
```
keep in mind that in the pipeline we trimmed problematic sites in the VCFs using problematic_sites_sarsCov2.vcf file. This VCF was constructed using SARS-CoV-2 reference genome NC_045512.2 and therefore, users should use this SARS-CoV-2 reference sequence in the pipeline, available here: 

https://www.ncbi.nlm.nih.gov/nuccore/NC_045512.2?report=fasta

Or in our repository (covid19-refseq.fasta)

You have to download and install this repository again to have access to SARS-CoV-2-FASTA-freebayes.

Let me know if works

Carlos.

**Comment by cfarkas** [comment] 2021-07-15 18:20
Hi IsabelEF

Yesterday I uploaded to the repository a new "Agnostic" FASTA variant
caller script, including the correspondent explanation on how to use it.
All of this, was based on your problem with the pipeline. Please let me
know if that helps.

Best Regards,

Carlos

**Comment by cfarkas** [comment] 2021-09-06 19:13
I will close this issue due inactivity

**Closed as completed by cfarkas** 2021-09-06 19:13 UTC
